SELECT TOP (1000) [id]
      ,[billing_id]
      ,[date]
      ,[customer_id]
      ,[employee_id]
      ,[product_id]
      ,[quantity]
      ,[region]
  FROM [bd_staging_2025_G06].[dbo].[stg_ventas_historicas_G06]
